/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    IEpCloseBold: typeof import('~icons/ep/close-bold')['default']
    IEpEdit: typeof import('~icons/ep/edit')['default']
    IEpSelect: typeof import('~icons/ep/select')['default']
    InputEdit: typeof import('./components/input-edit.vue')['default']
  }
}
